//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseApp.Resources.languag {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseApp.Resources.languag.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 Hours.
        /// </summary>
        internal static string _12Hours {
            get {
                return ResourceManager.GetString("12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Hours.
        /// </summary>
        internal static string _3Hours {
            get {
                return ResourceManager.GetString("3Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Hours.
        /// </summary>
        internal static string _6Hours {
            get {
                return ResourceManager.GetString("6Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Data.
        /// </summary>
        internal static string btnBackup {
            get {
                return ResourceManager.GetString("btnBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string btnDetails {
            get {
                return ResourceManager.GetString("btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Color.
        /// </summary>
        internal static string btnEditColor {
            get {
                return ResourceManager.GetString("btnEditColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Icon.
        /// </summary>
        internal static string btnEditicon {
            get {
                return ResourceManager.GetString("btnEditicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Data.
        /// </summary>
        internal static string btnRestor {
            get {
                return ResourceManager.GetString("btnRestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category Items.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you don&apos;t spend any mony today? Don&apos;t forget to log expenses..
        /// </summary>
        internal static string EmptyCollection {
            get {
                return ResourceManager.GetString("EmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string homeTitle {
            get {
                return ResourceManager.GetString("homeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languag.
        /// </summary>
        internal static string Languag {
            get {
                return ResourceManager.GetString("Languag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select action.
        /// </summary>
        internal static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Item.
        /// </summary>
        internal static string lblAddItem {
            get {
                return ResourceManager.GetString("lblAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Spent.
        /// </summary>
        internal static string lblAmountSpent {
            get {
                return ResourceManager.GetString("lblAmountSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and restore your data.
        /// </summary>
        internal static string lblBackup {
            get {
                return ResourceManager.GetString("lblBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Balance : The salary or the designated amount for monthly expenses.
        /// </summary>
        internal static string lblBalance {
            get {
                return ResourceManager.GetString("lblBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catigory.
        /// </summary>
        internal static string lblCatigory {
            get {
                return ResourceManager.GetString("lblCatigory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete message.
        /// </summary>
        internal static string lblDeleteMsg {
            get {
                return ResourceManager.GetString("lblDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailsMonthly.
        /// </summary>
        internal static string lblDetails {
            get {
                return ResourceManager.GetString("lblDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Type.
        /// </summary>
        internal static string lblExpenseType {
            get {
                return ResourceManager.GetString("lblExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expenses.
        /// </summary>
        internal static string lblExpMonth {
            get {
                return ResourceManager.GetString("lblExpMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Expenses.
        /// </summary>
        internal static string lblExpRecent {
            get {
                return ResourceManager.GetString("lblExpRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Expenses.
        /// </summary>
        internal static string lblExpToday {
            get {
                return ResourceManager.GetString("lblExpToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string lblHomeHello {
            get {
                return ResourceManager.GetString("lblHomeHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s record your expenses and don&apos;t forget to do it daily!.
        /// </summary>
        internal static string lblHomeWelcome {
            get {
                return ResourceManager.GetString("lblHomeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string lblItem {
            get {
                return ResourceManager.GetString("lblItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Name and avatar.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoI tems.
        /// </summary>
        internal static string lblNoItems {
            get {
                return ResourceManager.GetString("lblNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a reminder notification to log expenses svery.
        /// </summary>
        internal static string lblNoyify {
            get {
                return ResourceManager.GetString("lblNoyify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        internal static string lblPrix {
            get {
                return ResourceManager.GetString("lblPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblShellHome {
            get {
                return ResourceManager.GetString("lblShellHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string lblShellSetting {
            get {
                return ResourceManager.GetString("lblShellSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statestics.
        /// </summary>
        internal static string lblShellStatestic {
            get {
                return ResourceManager.GetString("lblShellStatestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total .
        /// </summary>
        internal static string lblStatisTotal {
            get {
                return ResourceManager.GetString("lblStatisTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly Expenses.
        /// </summary>
        internal static string lblStatisYearly {
            get {
                return ResourceManager.GetString("lblStatisYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Notifications.
        /// </summary>
        internal static string RecNotify {
            get {
                return ResourceManager.GetString("RecNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Notification Setting.
        /// </summary>
        internal static string SaveNotify {
            get {
                return ResourceManager.GetString("SaveNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string statisticTitle {
            get {
                return ResourceManager.GetString("statisticTitle", resourceCulture);
            }
        }
    }
}
